services:
  - type: web
    name: real-utility-savings
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:$PORT server:app"
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
